name: Hub
main: erase\hub\Hub

version: 1.0.0
api: 5.0.0

author: Erase (sheluvmyshe)
description: Simple Hub System for the Erase Network.

load: POSTWORLD

website: https://erasemc.com/

permissions:
  hub.command.setspawn:
    default: op
  hub.command.hub:
    default: true
  hub.bypass.protection:
    default: op
